#spring.main.banner-mode=off
#
#  # настройки доступа к базе через MySQL
#spring.datasource.url=jdbc:mysql://localhost/world?useSSL=false
#spring.datasource.username=newuser
#spring.datasource.password=1qazZAQ!
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#
#  # Поддерживаем соединение живым, если долго не было запросов мождет отвалиться
#spring.datasource.testWhileIdle = true
#spring.datasource.validationQuery = SELECT 1
#
#  # ===============================
#  # = JPA / HIBERNATE
#  # ===============================
#  # создавать и удалять базу, используя import.sql как дамп
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#  # Naming strategy
#spring.jpa.hibernate.naming-strategy = org.hibernate.cfg.ImprovedNamingStrategy
#  # Allows Hibernate to generate SQL optimized for a particular DBMS
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect


spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"

---

spring:
  profiles: dev
  server: localhost
  port: 8080

# ===============================
# DB
# ===============================
spring.datasource:
  url: jdbc:h2:mem:testdb
  driverClassName: org.h2.Driver
  username: sa
  password: password

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  show-sql: true
  #hibernate.ddl-auto: update
  #spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.H2Dialect


# To See H2 Console in Browser:
# http://localhost:8080/h2-console
# Enabling H2 Console
spring.h2.console.enabled: true


#**************************

#spring.datasource:
#  url: "jdbc:mysql://localhost/world?useSSL=false"
#  username: newuser
#  password: 1qazZAQ!
#  driver-class-name: com.mysql.jdbc.Driver
#  testWhileIdle: true
#  validation-query: "SELECT 1"



#spring.jpa:
#  hibernate:
#     ddl-auto: none
#     aming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#     dialect: org.hibernate.dialect.MySQL5Dialect
#  show-sql: true
